pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:jr_tutorials_000_031823/freecodecamp-org-godot-crash-course-for-beginners
          - cd freecodecamp-org-crash-course-for-beginners.git
          - git push --mirror git@github.com:josh-reeves/freecodecamp-org-godot-crash-course-for-beginners